language: dart
sudo: required
dart:
  - stable
  - beta
  - dev
before_script:
  - pub run tekartik_travis_ci_flutter:install
  - source $(pub run tekartik_travis_ci_flutter:env)
script:
  - dart tool/travis.dart
matrix:
  allow_failures:
    - dart: dev