language: dart
sudo: required
dist: trusty
dart:
  - stable
  - dev
before_script:
  - dart tool/travis_flutter_install.dart
  - source $(dart tool/travis_flutter_env.dart)
script:
  - dart tool/travis.dart
