name: tekartik_app_flutter_utils_repo
description: Repo
version: 0.1.0
homepage: https://www.example.com
author: alex <alex@tekartik.com>

environment:
  sdk: '>=2.7.0-dev <3.0.0'

dev_dependencies:
  tekartik_travis_ci_flutter:
    git:
      url: git://github.com/tekartik/travis_ci_flutter.dart
      ref: dart2
    version: '>=0.1.0'
  process_run: '>=0.10.3'
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.7.8'

  # include all from git so that it makes a dependency check
  tekartik_app_emit:
    git:
      url: git://github.com/tekartik/app_common_utils.dart
      ref: dart2
      path: app_emit

  test:

dependency_overrides:
  pedantic: '>=1.9.0'
# tmp
#  process_run:
#    path: ../process_run.dart